### PR TITLE
Insert argument templates 

### PR DESCRIPTION
**Pull request by TatriX**
Insert argument templates only when there are no arguments after completion.

### CODE REVIEW

**Comment by TatriX** [comment]
I was suffering from this behavior for about a year.
Now I'm happy ;)

**Comment by nsf** [comment]
:grin:

**Comment by TatriX** [comment]
Well actually I think there is a better solution: use two hotkeys: one to complete only function/method name and another one to complete it with templates.
It will fix my issue and also it will be possible to complete function name without parenthesis. It's required e.g. when I wish to pass a function as an argument.

What if ```RET``` will work as "full" completion and ```TAB``` as complete name only?

**Comment by nsf** [comment]
I honestly don't know. If you ask me I prefer seeing function signature separately and never using any kind of templates. But in some editors it's problematic, for example in sublime text 3 that I'm using right now. I know fancy GoSublime shows the signature in the status bar when you put cursor on the function, but I mean when you actually select autocompletion candidate.

So if we imagine a perfect text editor, I would say there should be a way to make a popup hint of some sort that stays for some time. Like you definitely need some sort of eye tracking here, as long as you look at the hint popup, it's relevant. Variants with pressing buttons or pedals are possible, but I don't know.

Very hard problem to solve. Contextual help that you need sometimes maybe if you really want to and for undefined amount of time. And you can't distract yourself managing this thing, because you're busy doing other things.

**Comment by TatriX** [comment]
Consider the following (bold - templates):
log.Out ```RET``` -> log.Output(**calldepth int**, **s string**)
log.Out ```TAB``` -> log.Ouput

In company-mode
```RET``` — company-complete-selection
```TAB``` — company-complete-common
so I think applying template on selection only makes sense.

**Comment by nsf** [comment]
Yes, I understand what you mean, but if we talk about company mode I think it's possible to do that outside of gocode. You just do two key bindings, one of which temporarly sets an option to disable templates. If users want that, they'll do it.

E.g. I have a binding which does something similar:

```lisp
; saving without NL at the end
(global-set-key (kbd "C-x S") (lambda ()
				(interactive)
				(let ((orig require-final-newline))
				  (setq require-final-newline nil)
				  (save-buffer)
				  (setq require-final-newline orig))))
```

Even though I rarely use emacs these days, I don't like when plugins redefine essential keys like RET and TAB.

We could just add that recipe to README.

**Comment by TatriX** [comment]
It would be great.

**Pull request merged**
