### PR TITLE
package_bin: Support go1.8 upstream

### PR DESCRIPTION
**Pull request by zchee**
The backport of https://github.com/golang/tools/commit/b2560d12f64dbcfe7229cdf58d59a6892a43ba00 and https://github.com/golang/tools/commit/2bbdb4568e161d12394da43e88b384c6be63928b.

Tested 1.6.3, 1.7 and `devel+9be2a27`, it seems have backward compatibility.

### CODE REVIEW

**Comment by zchee** [comment]
for other(I think @nsf already know)

gocode have not `pkg` variable `nil` check in the `fieldName` that
```go
	if pkg == nil {
		// use the imported package instead
		pkg = p.pkgList[0]
	}
```

but `aliasedPkgName` of `fieldName` function arguments is always have the `aliasedPkgName.alias`.
So it seems there is no need.

**Comment by nsf** [comment]
I honestly have no idea how package import system works in gocode anymore :D

Will test the patch myself on all versions and will merge it, I don't know, some time this week.

**Comment by zchee** [comment]
@nsf 
> I honestly have no idea how package import system works in gocode anymore :D

lol.
Since I read all `gocode` code of at least once, I can help if there was a problem lol

> Will test the patch myself on all versions and will merge it, I don't know, some time this week.

Thanks :)

**Comment by nsf** [comment]
Btw, thanks for the patch. I'm not big fan of maintaining compatibility with unreleased versions of Go.

**Comment by zchee** [comment]
@nsf Thanks for merge :)

> Btw, thanks for the patch. I'm not big fan of maintaining compatibility with unreleased versions of Go.

Ah, it means gocode the policy do not correspond to the version of the unstable? 
If so, I will support the latest with a fork. and it sends the PR after the stable version is released.

I have a branch that corresponds to the next upstream. Can I send it?
https://github.com/zchee/gocode/tree/package_bin/9deed8c

**Comment by zchee** [comment]
@nsf OK, I was misunderstood.
will sent PR :)

**Pull request merged**
