### PR TITLE
[WIP] Support binary version to 6

### PR DESCRIPTION
**Pull request by zchee**
write later

### CODE REVIEW

**Comment by zchee** [comment]
now implements...
https://github.com/golang/go/commit/ca2f85fd3f32b2a4c863a2de602876bd31e9d956

**Comment by Quasilyte** [comment]
@zchee, have you submitted that update? I don't see any changes in this pull request.
Or do you mean that you're only getting into it?

**Comment by zchee** [comment]
@Quasilyte I was pushed https://github.com/nsf/gocode/pull/512/files, but Go core runtime has been changed https://github.com/golang/go/commit/ca2f85fd3f32b2a4c863a2de602876bd31e9d956.
So, gocode panic again.

Now I try to following new binary parser into gocode.

**Comment by Quasilyte** [comment]
@zchee, I see. Thank you.

Everyone who is bound to go devel version wish you good luck. :+1:

**Comment by OneOfOne** [comment]
@Quasilyte https://github.com/mdempsky/gocode/ works for now, a little bit slower than this but beats not having auto completion with go devel.

Also I'm using it with the vgo PR from https://github.com/mdempsky/gocode/pull/26

**Comment by Quasilyte** [comment]
@OneOfOne, big thanks.

**Comment by zchee** [comment]
close via https://github.com/nsf/gocode/commit/f1f547fc1cd78d02c3343f6acca144b79d411f02

@nsf Thanks for commit!!

**Comment by zchee** [comment]
close via https://github.com/nsf/gocode/commit/f1f547fc1cd78d02c3343f6acca144b79d411f02

@nsf Thanks for commit!!

**Comment by nsf** [comment]
but keep in mind that I'm not going to add support for package cache or so called modules, in that sense it's worth looking for alternatives to gocode

**Comment by Quasilyte** [comment]
@nsf, thanks for your effort on gocode all this time. :+1:

**Comment by zchee** [comment]
I see. I continue to consider re-write gocode.

**Pull request closed without merging**
