### PR TITLE
Support ability to autobuild packages when using gb

### PR DESCRIPTION
**Pull request by evanphx**
The gb strategy did not have the code to autobuild packages like the other paths, so I went ahead and added it!

### CODE REVIEW

**Comment by nsf** [comment]
Sorry it took so long. But I don't like the patch. Seems like you're trying to build "gb" packages with "go/build"? Gb uses a completely different package structure. It's just not gonna work.

**Comment by evanphx** [comment]
I'm using it now and it works fine. Gb is go tool compatible if GOPATH is set correctly, which is what I'm doing.

**Comment by nsf** [comment]
Not really, gb tool creates directories for packages like that $GOOS-$GOARCH (e.g. linux-amd64) and go tool creates $GOOS_$GOARCH (e.g. linux_amd64). Notice the difference. Hyphen vs. underscore.

**Comment by evanphx** [comment]
Interesting. Well, my patch seemed to work for me. The built packages were
found and loaded by gocode

**Comment by nsf** [comment]
Which is rather weird. Can you try runnning gocode with debug mode? `gocode -s -debug` and see where it thinks the packages are? It shows the full path on autocompletion request there for every package.

**Pull request closed without merging**
