### PR TITLE
Auto closing gocode after some time without activity

### PR DESCRIPTION
**Pull request by msurdi**
Would you consider a feature like this one to be included in gocode?

Thanks.

### CODE REVIEW

**Comment by nsf** [comment]
I will most likely merge it tomorrow. I took a look at the patch, seems legit.

**Comment by msurdi** [comment]
It looks to me like the most controversial part is what to set as a default value for this.

**Comment by nsf** [comment]
Set it to true, that's okay.

**Comment by nsf** [comment]
Oh, you mean the value, I don't know, will take a look at it tomorrow. 20-30 minutes maybe.

**Pull request merged**
