### PR TITLE
patch for static library couldn't be rebuilt.

### PR DESCRIPTION
**Pull request by Iancurtis**

### CODE REVIEW

**Comment by nsf** [comment]
Hm... so, yeah, I can see it. But also I kind of disagree with this patch.

You see when you set gocode's `lib-path`, it means "look for packages in a completely custom place ignoring all Go environment conventions". And autobuilding when you find packages there seems really suspicious.

May I ask which editor uses `lib-path`? Or perhaps you use `lib-path` for whatever reason? This variable is a hack for really last resort cases and should not be normally used.

**Comment by Iancurtis** [comment]
thanks for your reply. A plugin named [vscode-go](https://github.com/Microsoft/vscode-go.git) in vscode maybe use the `lib-path`. I didn't dig into it. hope that you would give a perfect solution later:)

**Comment by nsf** [comment]
According to https://github.com/Microsoft/vscode-go/blob/master/src/goSuggest.ts, it doesn't set `lib-path`.

**Comment by nsf** [comment]
I would argue that `autobuild` shouldn't work when `lib-path` is set to true. Maybe I'll add that info to log output.

**Pull request closed without merging**
