### PR TITLE
Sublime3 plugin performance improvements

### PR DESCRIPTION
**Pull request by jeroenrinzema**
As mentioned at the `gocode` fork of @stamblerre [#13](https://github.com/stamblerre/gocode/issues/13). When trying to type in sublime does the view freeze until `gocode` has returned it's results. This pull requests makes all autocomplete requests called async and are synced with the active view once done.

**Before:**
48439430-894da080-e786-11e8-9ef9-b4825b953ec3

**After:**
48561207-c5504500-e8ef-11e8-9967-39ee1c1854b6

### CODE REVIEW

**Comment by jeroenrinzema** [comment]
@nsf Maybe an idea to include a settings option that disables the Sublime default textual autocomplete and only displays the results from `gocode`?

**Comment by nsf** [comment]
Thanks, will try it.

**Comment by frou** [comment]
Thanks for this. I have also been using (a modified version of) the Sublime code.

I just modified @jeroenrinzema's async completion to do the following to stop those uninteresting default completions from flashing up briefly: 

https://github.com/frou/GoFeather/blob/976469b29fdfc333e1a312703db7b5b3890a194c/plugin_autocomplete.py#L77-L101

**Comment by jeroenrinzema** [comment]
@frou Also already made a improved version of the `gocode` plugin [at stamblerre's fork of gocode](https://github.com/stamblerre/gocode/blob/master/subl3/gocode.py#L206). I still have to make a PR to this repo to update the plugin.

**Pull request merged**
