### PR TITLE
completion of import declaration doesn't work on windows.

### PR DESCRIPTION
**Pull request by mattn**
Fixes #332

### CODE REVIEW

**Comment by nsf** [comment]
I don't like the fix.

Maybe you could just replace the usage of "path/filepath" lib with "path"? I think it does POSIX paths by default everywhere.

**Comment by mattn** [comment]
> Maybe you could just replace the usage of "path/filepath" lib with "path"?

I just replace backslash into slash because the path separator is always backslash on windows.

**Comment by mattn** [comment]
If you want, I'll add checking of `runtime.GOOS`.

**Comment by mattn** [comment]
I'm thinking, filepath.ToSlash doesn't define that it works or doesn't works for partial strings.

**Comment by nsf** [comment]
No, I don't like the fact of replacement. When there is a function above which does concatenation. My suggestion is to fix concatenation so that it does the right thing. 

There is a path lib: https://golang.org/pkg/path/

It always uses the right kind of slash. You can just replace filepath usage with it.

**Comment by mattn** [comment]
Okay, however, docs should say `it works for partial strings too`, I think.

**Comment by nhooyr** [comment]
@mattn does #334 work for you?

**Pull request closed without merging**
