### PR TITLE
package_bin: improve efficiency of binary export position encoding

### PR DESCRIPTION
**Pull request by zchee**
Backports golang/go@a6b16e0([golang.org/cl/41619](https://golang.org/cl/41619))

Original commit message:

>   cmd/compile: improve efficiency of binary export position encoding
>   Use -64 instead of 0 as the magic "new file"
>   line delta, since it is much less common.
> 
>   Use a new path encoding that breaks up paths
>   into /-separated components, allowing
>   reuse of the component strings, and making
>   many re-used paths a single byte to encode.
> 
>   Bump the export version to 5.

It's based on Go core runtime changes, because `gcimporter15` package hasn't backporting now. If `golang.org/x/tools/go/gcimporter15` will different changes, I'll create a new pull request for future backport.

### CODE REVIEW

**Comment by zchee** [comment]
@nsf Ah, sorry. Please wait for merge.
It will works, but seems to `p.importpath` is unnecessary.

**Comment by zchee** [comment]
@nsf Deleted `p.importpath` and related things.
PTAL.

**Comment by OneOfOne** [comment]
I can confirm this fixes #452 for me.

**Comment by zchee** [comment]
@nsf Thanks merged :)

**Pull request merged**
