### PR TITLE
Register company-go with company-backends

### LINKED ISSUE #275: company-go backend isn't automatically loaded by company
The installation instructions for company-go say that company loads every backend it has by default. This didn't work for me. Only after adding the hook described in the same document the backend actually started working.

Either I have done something wrong (which is entirely possible), or the documentation is incorrect here, or there is a bug. Can someone clarify?

### PR DESCRIPTION
**Pull request by nicot**
Fixes #275.

### CODE REVIEW

**Comment by stardiviner** [comment]
I think this should be put in user configuration. Instead of default.
I use custom function to add company backend to default `company-backends` list.
My default `company-backends` list looks like this:
```lisp
((company-files company-keywords company-capf company-yasnippet) (company-abbrev
 company-dabbrev))
```
If gocode add `company-go` to `company-backends` by default, then other backends will not work.

**Comment by dgutov** [comment]
Yes, this is definitely non-idiomatic.

**Comment by nicot** [comment]
Whoops, I'm no emacs expert. Is there a way to have the backend added by default, but avoid clobbering your setup?

**Comment by dgutov** [comment]
There is, but it can't be fool-proof anyway.

Just have users add the necessary couple of lines to their init script, all other third-party backends do that.

**Comment by nicot** [comment]
OK. Here's an example of [another project](https://github.com/tonini/alchemist.el/blob/master/alchemist-company.el#L142) doing the same thing, but I'll revert it.

**Comment by dgutov** [comment]
[company-irony](https://github.com/Sarcasm/company-irony#configuration) has a good example.

**Comment by dgutov** [comment]
> Here's an example of another project doing the same thing

That's a good point, but Alchemist is a whole integrated environment, so I'd say it gets a pass.

**Pull request merged**
